Repository eggheads/eggdrop, pull requests merged in 2022-12, with the labels that each got.

#1359 Add systemd option to autobotchk
  INSTALL
  README
  doc/html/tutorials/firststeps.html
  doc/sphinx_source/install/install.rst
  doc/sphinx_source/install/readme.rst
  doc/sphinx_source/tutorials/firststeps.rst
  scripts/autobotchk
Labels: type: feature

#1370 Update bothost only on own chghost
  src/mod/server.mod/servmsg.c
Labels: type: bug

#1378 Fix links to binds
  doc/html/tutorials/firstscript.html
Labels: component: docs

#1345 Fix openssl3 deprecation
  src/tls.c
Labels: category: general
