Repository eggheads/eggdrop, pull requests merged in 2023-12, with the labels that each got.

#1513 Fix log for 900 (RPL_LOGGEDIN) and 901 (RPL_LOGGEDOUT)
  src/mod/server.mod/servmsg.c
Labels: category: general

#1432 Update doc
  doc/man1/eggdrop.1
  doc/sphinx_source/tutorials/setup.rst
  language/core.french.lang
  language/core.german.lang
  src/main.h
  src/mod/assoc.mod/language/assoc.portuguese.lang
  src/mod/filesys.mod/language/filesys.german.lang
  src/mod/transfer.mod/language/transfer.portuguese.lang
  src/userrec.c
Labels: component: docs

#1495 Add got-chanlist event bind type
  doc/sphinx_source/using/tcl-commands.rst
  src/mod/irc.mod/chan.c
  src/mod/module.h
  src/modules.c
  src/tclhash.c
  src/tclhash.h
  src/tclmisc.c
Labels: type: feature, Tcl

#1517 Various small doc updates
  doc/sphinx_source/modules/included.rst
  doc/sphinx_source/using/tcl-commands.rst
  src/mod/blowfish.mod/modinfo
Labels: component: docs
