Repository eggheads/eggdrop, pull requests merged in 2023-02, with the labels that each got.

#1381 Update Tcl repo
  configure
  configure.ac
  src/mod/compress.mod/configure
  src/mod/dns.mod/configure
Labels: component: docs

#1397 Doc/updatebotlink
  doc/sphinx_source/using/botnet.rst
Labels: component: docs

#1382 Fix crash - add missing Tcl_UntraceVar(keep-nick)
  src/mod/twitch.mod/twitch.c
Labels: type: bug, Category: module

#1402 Workaround for usage of Emoji with default TCL_UTF_MAX==3
  src/tcl.c
Labels: type: bug, category: general

#1387 Add ssl header version to .status
  src/chanprog.c
  src/lang.h
Labels: category: general

#1394 revert bind char change
  src/flags.c
  src/tclhash.c
Labels: type: bug, category: general

#1383 Woobie tutorial
  doc/html/index.html
  doc/html/modules/internals.html
  doc/html/tutorials/module.html
  doc/sphinx_source/index.rst
  doc/sphinx_source/modules/internals.rst
  doc/sphinx_source/modules/writing.rst
  doc/sphinx_source/tutorials/module.rst
Labels: component: docs, Category: module

#1407 Raise minimum Tcl requirement to 8.5
  aclocal.m4
  config.h.in
  configure.ac
  doc/BUG-REPORT
  src/main.c
  src/main.h
  src/tcl.c
Labels: component: docs, component: compilation, category: API change, category: general

#1353 Fix crash - add tcl service mode hook stub / enhance doc
  INSTALL
  doc/COMPILE-GUIDE
  src/tcl.c
Labels: category: general

#1348 Replace deprecated / obsolete gethostbyname2() with POSIX.1-2001 getaddrinfo()
  aclocal.m4
  src/Makefile.in
  src/compat/Makefile.in
  src/compat/compat.h
  src/compat/gethostbyname2.c
  src/compat/gethostbyname2.h
  src/md5/Makefile.in
  src/net.c
  src/tcldcc.c
Labels: category: general
