Repository eggheads/eggdrop, pull requests merged in 2024-12, with the labels that each got.

#1695 Fix things not working when there is a bind log
  src/tclhash.c
Labels: type: bug

#1702 Crash fix .restart with python.mod
  src/main.c
  src/mod/python.mod/Makefile.in
  src/mod/python.mod/python.c
Labels: type: bug, Python

#1712 DOC : Correct mod-path variable
  doc/sphinx_source/using/core.rst
Labels: component: docs

#1703 Fix python thread
  src/tcl.c
Labels: Python
