Repository eggheads/eggdrop, pull requests merged in 2024-07, with the labels that each got.

#1569 Add tcl pbkdf2 function
  doc/sphinx_source/using/tcl-commands.rst
  src/mod/pbkdf2.mod/pbkdf2.c
  src/mod/pbkdf2.mod/tclpbkdf2.c
Labels: type: feature, Tcl

#1647 python.mod venv support
  src/mod/python.mod/python.c
Labels: Python

#1650 Python unbind functionality
  src/mod/python.mod/pycmds.c
Labels: Python

#1654 Missed a Tcl_Size in the dns module
  src/mod/dns.mod/dns.c
Labels: Python

#1641 Document minimum library versions
  doc/sphinx_source/install/readme.rst
  doc/sphinx_source/using/tls.rst
Labels: component: docs

#1638 Cleanup python.mod includes
  src/mod/python.mod/Makefile.in
  src/mod/python.mod/python.c
Labels: Python

#1656 Fix utimer name duplication check
  src/tclmisc.c
Labels: type: bug

#1621 Fix include sys/resource.h
  src/chanprog.c
  src/cmds.c
  src/eggdrop.h
  src/main.c
  src/mod/pbkdf2.mod/pbkdf2.c
  src/tclhash.c
Labels: type: bug

#1658 Update Tcl doc with need-* guidance
  doc/sphinx_source/using/tcl-commands.rst
Labels: component: docs

#1659 Update tcl-commands.rst
  doc/sphinx_source/using/tcl-commands.rst
Labels: component: docs

#1593 Fix getchanjoin() - set joined time for bot on got352or4()
  src/mod/irc.mod/chan.c
Labels: type: bug

#1644 Enhance debug compiler flags
  aclocal.m4
  m4/ax_check_compile_flag.m4
Labels: component: compilation

#1584 Update autobotchk
  scripts/autobotchk
Labels: category: general

#1526 core.french.lang fix typos and improve readability
  language/core.french.lang
Labels: component: language

#1661 Convert encoding of language files to utf-8
  language/core.danish.lang
  language/core.finnish.lang
  language/core.french.lang
  src/mod/assoc.mod/language/assoc.danish.lang
  src/mod/assoc.mod/language/assoc.finnish.lang
  src/mod/assoc.mod/language/assoc.french.lang
  src/mod/console.mod/language/console.finnish.lang
  src/mod/console.mod/language/console.french.lang
  src/mod/filesys.mod/language/filesys.danish.lang
  src/mod/filesys.mod/language/filesys.finnish.lang
  src/mod/filesys.mod/language/filesys.french.lang
  src/mod/notes.mod/language/notes.danish.lang
  src/mod/notes.mod/language/notes.finnish.lang
  src/mod/notes.mod/language/notes.french.lang
  src/mod/transfer.mod/language/transfer.danish.lang
  src/mod/transfer.mod/language/transfer.finnish.lang
  src/mod/transfer.mod/language/transfer.french.lang
Labels: component: language
