Repository eggheads/eggdrop, pull requests merged in 2024-01, with the labels that each got.

#1518 Replace hard-coded docs version with variable
  doc/html/tutorials/setup.html
  doc/sphinx_source/conf.py
  doc/sphinx_source/modules/index.rst
  doc/sphinx_source/tutorials/setup.rst
  doc/sphinx_source/using/text-sub.rst
Labels: component: docs

#1506 Fix ssl read
  src/Makefile.in
  src/eggdrop.h
  src/main.c
  src/net.c
Labels: type: bug, category: general

#1510 Remove copy-to-tmp option
  doc/sphinx_source/modules/mod/transfer.rst
  doc/sphinx_source/using/tcl-commands.rst
  eggdrop.conf
  src/dccutil.c
  src/mod/filesys.mod/filesys.c
  src/mod/share.mod/share.c
  src/mod/transfer.mod/help/set/transfer.help
  src/mod/transfer.mod/help/transfer.help
  src/mod/transfer.mod/transfer.c
  src/modules.c
  src/tcl.c
  src/users.c
Labels: type: task, category: config, component: core

#1515 Add Python intpreter to Eggdrop
  .gitignore
  Makefile.in
  aclocal.m4
  configure
  configure.ac
  doc/sphinx_source/modules/mod/python.rst
  doc/sphinx_source/using/tcl-commands.rst
  m4/python.m4
  src/main.c
  src/mod/Makefile.in
  src/mod/module.h
  src/mod/python.mod/Makefile.in
  src/mod/python.mod/configure
  src/mod/python.mod/configure.ac
  src/mod/python.mod/pycmds.c
  src/mod/python.mod/pymod.h
  src/mod/python.mod/python.c
  src/mod/python.mod/python.h
  src/mod/python.mod/scripts/bestfriend.py
  src/mod/python.mod/scripts/greet.py
  src/mod/python.mod/scripts/imdb.py
  src/mod/python.mod/scripts/listtls.py
  src/mod/python.mod/scripts/urlTitle.py
  src/mod/python.mod/tclpython.c
  src/modules.c
  src/tclhash.c
  src/tclhash.h
Labels: type: feature

#1477 remove quick-logs, line buffer instead
  doc/sphinx_source/tutorials/setup.rst
  doc/sphinx_source/using/core.rst
  eggdrop.conf
  help/core.help
  help/set/cmds1.help
  src/main.c
  src/misc.c
  src/proto.h
  src/tcl.c
Labels: category: config

#1521 Add bind defined values to docs
  doc/html/tutorials/module.html
  doc/sphinx_source/modules/internals.rst
  doc/sphinx_source/tutorials/module.rst
Labels: component: docs

#1525 Properly report channel bans in .bans
  src/mod/channels.mod/userchan.c
Labels: component: core, category: general

#1374 Add userhost-in-names capability
  doc/sphinx_source/using/ircv3.rst
  src/mod/irc.mod/chan.c
  src/mod/server.mod/isupport.c
  src/mod/server.mod/server.c
  src/mod/server.mod/server.h
Labels: type: feature, category: general

#1530 Fix for SSL_get_server_tmp_key is not available for openssl < 1.0.2
  src/tls.c
Labels: type: bug
