Repository eggheads/eggdrop, pull requests merged in 2025-06, with the labels that each got.

#1821 Add python script tutorial
  doc/sphinx_source/tutorials/firstscript.rst
  eggdrop-basic.conf
  eggdrop.conf
Labels: component: docs

#1681 Crashfix read_lang() on malformed language file
  src/language.c
Labels: type: bug

#1547 Crashfix bot_away()
  src/botcmd.c
  src/botmsg.c
  src/mod/assoc.mod/assoc.c
Labels: type: bug

#1822 Remove case sensitivity in bind replacement
  src/tclhash.c
Labels: type: bug

#1722 Fix .tcl server add/remove arg parsing
  src/mod/server.mod/tclserv.c
Labels: type: bug

#1767 Doc update: Delete orphaned html files
  doc/html/modules/assoc.html
  doc/html/modules/blowfish.html
  doc/html/modules/channels.html
  doc/html/modules/compress.html
  doc/html/modules/console.html
  doc/html/modules/ctcp.html
  doc/html/modules/dns.html
  doc/html/modules/filesys.html
  doc/html/modules/ident.html
  doc/html/modules/irc.html
  doc/html/modules/mod/index.html
  doc/html/modules/notes.html
  doc/html/modules/pbkdf2.html
  doc/html/modules/seen.html
  doc/html/modules/server.html
  doc/html/modules/share.html
  doc/html/modules/transfer.html
  doc/html/modules/twitch.html
  doc/html/modules/uptime.html
  doc/html/modules/woobie.html
  doc/html/using/pbkdf2.html
  doc/html/using/twitch.html
  doc/sphinx_source/index.rst
Labels: component: docs

#1749 Fix python.mod make error
  src/mod/python.mod/configure.ac
  src/mod/python.mod/pycmds.c
  src/mod/python.mod/python.c
  src/mod/python.mod/python.h
Labels: Category: module
